inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance # 拡張機能
  - rubocop-rails # 拡張機能
  - rubocop-rspec # 拡張機能

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.1

Rails/I18nLocaleTexts:
  Enabled: false

Rails/ActionControllerFlashBeforeRender:
  Exclude:
    - "app/controllers/sessions_controller.rb"

Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Rails/ActionOrder:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
